chore: Update all references of 'Twitter' to 'X.com'
hemilabs/CryptoChords pull request #99
Opened 2024-11-27 13:47 UTC by NikolaiKryshnev

2024-12-23 18:03 UTC, ArturDolzan requested changes

2024-12-23 18:03 UTC, ArturDolzan commented on CONTRIBUTING.md
> +- [Twitter](https://x.com/hemi_xyz)
Let's update all references
```suggestion
- [X](https://x.com/hemi_xyz)
```

2024-12-23 18:33 UTC, ArturDolzan approved these changes

2024-12-23 18:38 UTC, gndelia approved these changes

2024-12-26 18:35 UTC, rafappelt approved these changes

2024-12-26 19:03 UTC, gndelia commented
@NikolaiKryshnev  one of your 2 commits is not signed. Please rebase signing all your commits!

2024-12-27 13:19 UTC, merged